AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-sawarame

  SAM Template for api-sawarame

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  ApiSawarame:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # ここでリソースポリシーを定義します
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Deny
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource: "execute-api:/*"
              Condition:
                StringNotLike:
                  "aws:Referer":
                    - "https://sawara.me/*"
            - Effect: Allow
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource: "execute-api:/*"
  V1GetIpaddressFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/v1/get_ipaddress/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/ipaddress
            Method: get
            RestApiId: !Ref ApiSawarame

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  V1GetIpaddressApi:
    Description: API Gateway endpoint URL for Prod stage for get ip address function
    Value: !Sub "https://${ApiSawarame}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/v1/ipaddress/"
  V1GetIpaddressFunction:
    Description: get ip address Lambda Function ARN
    Value: !GetAtt V1GetIpaddressFunction.Arn
  V1GetIpaddressFunctionIamRole:
    Description: Implicit IAM Role created for get ip address function
    Value: !GetAtt V1GetIpaddressFunctionRole.Arn
